import NavBar from "@/components/NavBar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lavender", padding: "25px"}}>
        <NavBar/>
        </header>
        {children}
        <footer style={{backgroundColor: "lightgray", padding: "10px"}}></footer>
      </body>
      
    </html>
  )
}
